{{- define "kubeStateMetricsCore-config" -}}
kubernetes_state_core.yaml.default: |-
{{- if .Values.datadog.kubeStateMetricsCore.useClusterCheckRunners }}
  cluster_check: true
{{- end }}
  init_config:
  instances:
    - collectors:
{{- if .Values.datadog.kubeStateMetricsCore.collectSecretMetrics }}
      - secrets
{{- end }}
      - cronjobs
      - daemonsets
      - deployments
      - endpoints
      - horizontalpodautoscalers
      - jobs
      - limitranges
      - namespaces
      - nodes
      - persistentvolumeclaims
      - persistentvolumes
      - poddisruptionbudgets
      - pods
      - replicasets
      - replicationcontrollers
      - resourcequotas
      - services
      - statefulsets
      - storageclasses
      - verticalpodautoscalers
      - volumeattachments
{{- if .Values.datadog.kubeStateMetricsCore.useClusterCheckRunners }}
      skip_leader_election: true
{{- end }}
      labels_as_tags:
{{ .Values.datadog.kubeStateMetricsCore.labelsAsTags | toYaml | indent 10 }}
{{- end -}}
